name: Build and test
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "This job's status is ${{ job.status }}."
  build:
    runs-on: ubuntu-latest
